export class InvoicesDataItem {
    public constructor(init: Partial<InvoicesDataItem>) {
        Object.assign(this, init);
    }

    public ShipName: string;
    public ShipAddress: string;
    public ShipCity: string;
    public ShipPostalCode: number;
    public ShipCountry: string;
    public ShipRegion: string;
    public ShipperName: string;
    public CustomerID: number;
    public CustomerName: string;
    public CustomerFirstName: string;
    public CustomerLastName: string;
    public CustomerAddress: string;
    public Salesperson: string;
    public OrderID: number;
    public OrderDate: string;
    public ProductID: number;
    public ProductName: string;
    public UnitPrice: number;
    public Quantity: number;
    public ExtendedPrice: number;
    public Freight: number;
    public Discontinued: boolean;
    public Region: string;
    public Address: string;
    public City: string;
    public Country: string;
    public PostalCode: number;

}
export class InvoicesData extends Array<InvoicesDataItem> {
    public constructor() {
        super();
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Home`,
            ShipAddress: `124 Wall Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 60098,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1000,
            CustomerName: `Martin Jefferson`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `124 Wall Street, Miami, USA, 60098`,
            Salesperson: `Nancy Jefferson`,
            OrderID: 1931,
            OrderDate: `3/14/2022`,
            ProductID: 189,
            ProductName: `IPad`,
            UnitPrice: 16150.61,
            Quantity: 3,
            ExtendedPrice: 48451.83,
            Freight: 980.61,
            Discontinued: false,
            Region: `South East`,
            Address: `124 Wall Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 60098
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Home`,
            ShipAddress: `162 Main Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 80193,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1001,
            CustomerName: `Anna Black`,
            CustomerFirstName: `Anna`,
            CustomerLastName: `Black`,
            CustomerAddress: `162 Main Street, Miami, USA, 80193`,
            Salesperson: `Anna Smith`,
            OrderID: 1163,
            OrderDate: `5/22/2022`,
            ProductID: 138,
            ProductName: `Mac Book Pro`,
            UnitPrice: 18520.59,
            Quantity: 4,
            ExtendedPrice: 74082.36,
            Freight: 850.59,
            Discontinued: false,
            Region: `West`,
            Address: `162 Main Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 80193
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Townhouse`,
            ShipAddress: `164 Wall Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 50111,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1002,
            CustomerName: `Max Watson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Watson`,
            CustomerAddress: `164 Wall Street, Miami, USA, 50111`,
            Salesperson: `Martin Watson`,
            OrderID: 1230,
            OrderDate: `2/9/2022`,
            ProductID: 118,
            ProductName: `Mac Book Air`,
            UnitPrice: 25310.39,
            Quantity: 3,
            ExtendedPrice: 75931.17,
            Freight: 210.39,
            Discontinued: false,
            Region: `West`,
            Address: `164 Wall Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 50111
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Townhouse`,
            ShipAddress: `124 Market Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 90123,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1003,
            CustomerName: `Max Madison`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Madison`,
            CustomerAddress: `124 Market Street, Philadelphia, USA, 90123`,
            Salesperson: `Anna Black`,
            OrderID: 1176,
            OrderDate: `6/3/2022`,
            ProductID: 169,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 29890.86,
            Quantity: 4,
            ExtendedPrice: 119563.44,
            Freight: 800.86,
            Discontinued: false,
            Region: `South East`,
            Address: `124 Market Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 90123
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Townhouse`,
            ShipAddress: `181 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 90095,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1004,
            CustomerName: `Pamela Jackson`,
            CustomerFirstName: `Pamela`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `181 Market Street, Miami, USA, 90095`,
            Salesperson: `Max Black`,
            OrderID: 1382,
            OrderDate: `1/10/2022`,
            ProductID: 185,
            ProductName: `Samsung Note`,
            UnitPrice: 7810.61,
            Quantity: 2,
            ExtendedPrice: 15621.22,
            Freight: 1790.61,
            Discontinued: false,
            Region: `West`,
            Address: `181 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 90095
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Home`,
            ShipAddress: `188 Wall Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 50149,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1005,
            CustomerName: `Mike Jefferson`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `188 Wall Street, Los Angeles, USA, 50149`,
            Salesperson: `Martin Jefferson`,
            OrderID: 1864,
            OrderDate: `8/18/2022`,
            ProductID: 168,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 9370.76,
            Quantity: 4,
            ExtendedPrice: 37483.04,
            Freight: 970.76,
            Discontinued: false,
            Region: `North East`,
            Address: `188 Wall Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 50149
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Home`,
            ShipAddress: `174 Market Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 90112,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1006,
            CustomerName: `Martin Smith`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Smith`,
            CustomerAddress: `174 Market Street, Huston, USA, 90112`,
            Salesperson: `Nancy Smith`,
            OrderID: 1502,
            OrderDate: `6/13/2022`,
            ProductID: 199,
            ProductName: `IPhone`,
            UnitPrice: 20830.47,
            Quantity: 2,
            ExtendedPrice: 41660.94,
            Freight: 1530.47,
            Discontinued: false,
            Region: `West`,
            Address: `174 Market Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 90112
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Townhouse`,
            ShipAddress: `134 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 50083,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1007,
            CustomerName: `Nancy Jefferson`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `134 Market Street, Miami, USA, 50083`,
            Salesperson: `Mike Jefferson`,
            OrderID: 1305,
            OrderDate: `10/21/2022`,
            ProductID: 185,
            ProductName: `Mac Book Air`,
            UnitPrice: 7320.44,
            Quantity: 2,
            ExtendedPrice: 14640.88,
            Freight: 630.44,
            Discontinued: false,
            Region: `West`,
            Address: `134 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 50083
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Estate`,
            ShipAddress: `177 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 70185,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1008,
            CustomerName: `Nancy Jefferson`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `177 Main Street, New York, USA, 70185`,
            Salesperson: `Pamela Watson`,
            OrderID: 1725,
            OrderDate: `5/7/2022`,
            ProductID: 133,
            ProductName: `Mac Book Air`,
            UnitPrice: 11240.72,
            Quantity: 3,
            ExtendedPrice: 33722.16,
            Freight: 420.72,
            Discontinued: false,
            Region: `South East`,
            Address: `177 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 70185
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Estate`,
            ShipAddress: `169 Main Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 90183,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1009,
            CustomerName: `Mike Jefferson`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `169 Main Street, Miami, USA, 90183`,
            Salesperson: `Anna Watson`,
            OrderID: 1977,
            OrderDate: `10/14/2022`,
            ProductID: 178,
            ProductName: `IPhone`,
            UnitPrice: 6460.55,
            Quantity: 3,
            ExtendedPrice: 19381.65,
            Freight: 370.55,
            Discontinued: true,
            Region: `South East`,
            Address: `169 Main Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 90183
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Estate`,
            ShipAddress: `151 Market Street`,
            ShipCity: `New York`,
            ShipPostalCode: 80160,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1010,
            CustomerName: `James Jackson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `151 Market Street, New York, USA, 80160`,
            Salesperson: `Nancy Black`,
            OrderID: 1666,
            OrderDate: `12/6/2022`,
            ProductID: 140,
            ProductName: `Mac Book Pro`,
            UnitPrice: 7940.82,
            Quantity: 2,
            ExtendedPrice: 15881.64,
            Freight: 1670.82,
            Discontinued: false,
            Region: `South East`,
            Address: `151 Market Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 80160
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Market`,
            ShipAddress: `147 Main Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 80183,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1011,
            CustomerName: `James Jefferson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `147 Main Street, Miami, USA, 80183`,
            Salesperson: `Mike Madison`,
            OrderID: 1059,
            OrderDate: `5/14/2022`,
            ProductID: 174,
            ProductName: `Samsung Note`,
            UnitPrice: 14650.56,
            Quantity: 2,
            ExtendedPrice: 29301.12,
            Freight: 1770.56,
            Discontinued: false,
            Region: `West`,
            Address: `147 Main Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 80183
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Estate`,
            ShipAddress: `134 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 80066,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1012,
            CustomerName: `Mike Watson`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Watson`,
            CustomerAddress: `134 Main Street, New York, USA, 80066`,
            Salesperson: `Mike Black`,
            OrderID: 1851,
            OrderDate: `7/24/2022`,
            ProductID: 175,
            ProductName: `IPhone`,
            UnitPrice: 7870.39,
            Quantity: 2,
            ExtendedPrice: 15740.78,
            Freight: 360.39,
            Discontinued: false,
            Region: `West`,
            Address: `134 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 80066
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Estate`,
            ShipAddress: `159 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 80096,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1013,
            CustomerName: `Ben Madison`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Madison`,
            CustomerAddress: `159 Market Street, Los Angeles, USA, 80096`,
            Salesperson: `Anna Madison`,
            OrderID: 1451,
            OrderDate: `10/4/2022`,
            ProductID: 188,
            ProductName: `Mac Book Pro`,
            UnitPrice: 13920.38,
            Quantity: 4,
            ExtendedPrice: 55681.52,
            Freight: 1140.38,
            Discontinued: false,
            Region: `North East`,
            Address: `159 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 80096
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Estate`,
            ShipAddress: `187 Wall Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 60144,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1014,
            CustomerName: `Martin Madison`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Madison`,
            CustomerAddress: `187 Wall Street, Miami, USA, 60144`,
            Salesperson: `Ben Jefferson`,
            OrderID: 1331,
            OrderDate: `4/4/2022`,
            ProductID: 119,
            ProductName: `IPhone`,
            UnitPrice: 6940.73,
            Quantity: 5,
            ExtendedPrice: 34703.65,
            Freight: 640.73,
            Discontinued: false,
            Region: `West`,
            Address: `187 Wall Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 60144
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Townhouse`,
            ShipAddress: `158 Wall Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 60063,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1015,
            CustomerName: `Ben Jackson`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `158 Wall Street, Huston, USA, 60063`,
            Salesperson: `Martin Jefferson`,
            OrderID: 1609,
            OrderDate: `9/6/2022`,
            ProductID: 171,
            ProductName: `IPhone`,
            UnitPrice: 29080.28,
            Quantity: 2,
            ExtendedPrice: 58160.56,
            Freight: 1810.28,
            Discontinued: false,
            Region: `South East`,
            Address: `158 Wall Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 60063
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Market`,
            ShipAddress: `168 Main Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 60184,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1016,
            CustomerName: `James Black`,
            CustomerFirstName: `James`,
            CustomerLastName: `Black`,
            CustomerAddress: `168 Main Street, Huston, USA, 60184`,
            Salesperson: `Martin Watson`,
            OrderID: 1772,
            OrderDate: `3/20/2022`,
            ProductID: 152,
            ProductName: `Mac Book Air`,
            UnitPrice: 28350.9,
            Quantity: 5,
            ExtendedPrice: 141754.5,
            Freight: 1290.9,
            Discontinued: false,
            Region: `South East`,
            Address: `168 Main Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 60184
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Market`,
            ShipAddress: `116 Main Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 60129,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1017,
            CustomerName: `Nancy Black`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Black`,
            CustomerAddress: `116 Main Street, Miami, USA, 60129`,
            Salesperson: `Nancy Smith`,
            OrderID: 1792,
            OrderDate: `9/1/2022`,
            ProductID: 182,
            ProductName: `Samsung Note`,
            UnitPrice: 13730.78,
            Quantity: 4,
            ExtendedPrice: 54923.12,
            Freight: 740.78,
            Discontinued: false,
            Region: `North East`,
            Address: `116 Main Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 60129
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Market`,
            ShipAddress: `116 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 80090,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1018,
            CustomerName: `Martin Madison`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Madison`,
            CustomerAddress: `116 Market Street, Los Angeles, USA, 80090`,
            Salesperson: `Anna Madison`,
            OrderID: 1285,
            OrderDate: `10/21/2022`,
            ProductID: 157,
            ProductName: `Mac Book Pro`,
            UnitPrice: 8120.36,
            Quantity: 3,
            ExtendedPrice: 24361.08,
            Freight: 410.36,
            Discontinued: false,
            Region: `West`,
            Address: `116 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 80090
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Townhouse`,
            ShipAddress: `135 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 90101,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1019,
            CustomerName: `Max Jefferson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `135 Wall Street, Philadelphia, USA, 90101`,
            Salesperson: `Mike Madison`,
            OrderID: 1205,
            OrderDate: `12/22/2022`,
            ProductID: 153,
            ProductName: `Mac Book Pro`,
            UnitPrice: 11830.22,
            Quantity: 2,
            ExtendedPrice: 23660.44,
            Freight: 330.22,
            Discontinued: true,
            Region: `North East`,
            Address: `135 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 90101
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Home`,
            ShipAddress: `164 Market Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 70056,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1020,
            CustomerName: `James Smith`,
            CustomerFirstName: `James`,
            CustomerLastName: `Smith`,
            CustomerAddress: `164 Market Street, Philadelphia, USA, 70056`,
            Salesperson: `Ben Watson`,
            OrderID: 1759,
            OrderDate: `8/3/2022`,
            ProductID: 129,
            ProductName: `Mac Book Pro`,
            UnitPrice: 15140.82,
            Quantity: 4,
            ExtendedPrice: 60563.28,
            Freight: 1400.82,
            Discontinued: false,
            Region: `South East`,
            Address: `164 Market Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 70056
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Estate`,
            ShipAddress: `196 Wall Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 90169,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1021,
            CustomerName: `Max Madison`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Madison`,
            CustomerAddress: `196 Wall Street, Miami, USA, 90169`,
            Salesperson: `Mike Smith`,
            OrderID: 1879,
            OrderDate: `8/17/2022`,
            ProductID: 127,
            ProductName: `Mac Book Air`,
            UnitPrice: 26710.41,
            Quantity: 5,
            ExtendedPrice: 133552.05,
            Freight: 1810.41,
            Discontinued: false,
            Region: `West`,
            Address: `196 Wall Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 90169
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Market`,
            ShipAddress: `175 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 50142,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1022,
            CustomerName: `Nancy Black`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Black`,
            CustomerAddress: `175 Wall Street, Philadelphia, USA, 50142`,
            Salesperson: `Anna Jefferson`,
            OrderID: 1917,
            OrderDate: `3/6/2022`,
            ProductID: 114,
            ProductName: `IPad`,
            UnitPrice: 9640.51,
            Quantity: 3,
            ExtendedPrice: 28921.53,
            Freight: 840.51,
            Discontinued: false,
            Region: `North East`,
            Address: `175 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 50142
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Home`,
            ShipAddress: `122 Main Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 60097,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1023,
            CustomerName: `Pamela Black`,
            CustomerFirstName: `Pamela`,
            CustomerLastName: `Black`,
            CustomerAddress: `122 Main Street, Los Angeles, USA, 60097`,
            Salesperson: `James Black`,
            OrderID: 1176,
            OrderDate: `8/4/2022`,
            ProductID: 197,
            ProductName: `IPad`,
            UnitPrice: 14500.56,
            Quantity: 4,
            ExtendedPrice: 58002.24,
            Freight: 530.56,
            Discontinued: false,
            Region: `West`,
            Address: `122 Main Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 60097
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Home`,
            ShipAddress: `139 Main Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 60175,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1024,
            CustomerName: `James Smith`,
            CustomerFirstName: `James`,
            CustomerLastName: `Smith`,
            CustomerAddress: `139 Main Street, Miami, USA, 60175`,
            Salesperson: `Mike Jefferson`,
            OrderID: 1317,
            OrderDate: `5/21/2022`,
            ProductID: 115,
            ProductName: `Mac Book Air`,
            UnitPrice: 17200.82,
            Quantity: 2,
            ExtendedPrice: 34401.64,
            Freight: 1610.82,
            Discontinued: false,
            Region: `West`,
            Address: `139 Main Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 60175
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Townhouse`,
            ShipAddress: `155 Market Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 60124,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1025,
            CustomerName: `James Watson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Watson`,
            CustomerAddress: `155 Market Street, Philadelphia, USA, 60124`,
            Salesperson: `Max Smith`,
            OrderID: 1721,
            OrderDate: `6/15/2022`,
            ProductID: 197,
            ProductName: `Samsung Note`,
            UnitPrice: 9810.3,
            Quantity: 2,
            ExtendedPrice: 19620.6,
            Freight: 1990.3,
            Discontinued: false,
            Region: `South East`,
            Address: `155 Market Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 60124
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Townhouse`,
            ShipAddress: `136 Main Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 80120,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1026,
            CustomerName: `Ben Jackson`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `136 Main Street, Philadelphia, USA, 80120`,
            Salesperson: `Max Smith`,
            OrderID: 1266,
            OrderDate: `12/13/2022`,
            ProductID: 198,
            ProductName: `Mac Book Pro`,
            UnitPrice: 25410.64,
            Quantity: 2,
            ExtendedPrice: 50821.28,
            Freight: 1860.64,
            Discontinued: false,
            Region: `West`,
            Address: `136 Main Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 80120
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Estate`,
            ShipAddress: `114 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 60186,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1027,
            CustomerName: `Max Jackson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `114 Main Street, New York, USA, 60186`,
            Salesperson: `Mike Jefferson`,
            OrderID: 1636,
            OrderDate: `7/7/2022`,
            ProductID: 174,
            ProductName: `Mac Book Pro`,
            UnitPrice: 13740.7,
            Quantity: 4,
            ExtendedPrice: 54962.8,
            Freight: 1960.7,
            Discontinued: false,
            Region: `West`,
            Address: `114 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 60186
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Home`,
            ShipAddress: `167 Market Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 70193,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1028,
            CustomerName: `Nancy Jefferson`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `167 Market Street, Huston, USA, 70193`,
            Salesperson: `Ben Jefferson`,
            OrderID: 1689,
            OrderDate: `1/2/2022`,
            ProductID: 192,
            ProductName: `IPad`,
            UnitPrice: 8760.83,
            Quantity: 3,
            ExtendedPrice: 26282.49,
            Freight: 490.83,
            Discontinued: false,
            Region: `South East`,
            Address: `167 Market Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 70193
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Home`,
            ShipAddress: `139 Wall Street`,
            ShipCity: `New York`,
            ShipPostalCode: 80080,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1029,
            CustomerName: `Anna Madison`,
            CustomerFirstName: `Anna`,
            CustomerLastName: `Madison`,
            CustomerAddress: `139 Wall Street, New York, USA, 80080`,
            Salesperson: `Anna Black`,
            OrderID: 1610,
            OrderDate: `3/17/2022`,
            ProductID: 105,
            ProductName: `Mac Book Pro`,
            UnitPrice: 19860.82,
            Quantity: 3,
            ExtendedPrice: 59582.46,
            Freight: 1990.82,
            Discontinued: true,
            Region: `West`,
            Address: `139 Wall Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 80080
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Home`,
            ShipAddress: `173 Market Street`,
            ShipCity: `New York`,
            ShipPostalCode: 70054,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1030,
            CustomerName: `Ben Madison`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Madison`,
            CustomerAddress: `173 Market Street, New York, USA, 70054`,
            Salesperson: `Ben Jackson`,
            OrderID: 1404,
            OrderDate: `12/8/2022`,
            ProductID: 171,
            ProductName: `IPhone`,
            UnitPrice: 12430.21,
            Quantity: 3,
            ExtendedPrice: 37290.63,
            Freight: 880.21,
            Discontinued: false,
            Region: `West`,
            Address: `173 Market Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 70054
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Market`,
            ShipAddress: `187 Wall Street`,
            ShipCity: `New York`,
            ShipPostalCode: 60100,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1031,
            CustomerName: `Mike Jefferson`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `187 Wall Street, New York, USA, 60100`,
            Salesperson: `Nancy Smith`,
            OrderID: 1480,
            OrderDate: `2/8/2022`,
            ProductID: 181,
            ProductName: `IPad`,
            UnitPrice: 26730.66,
            Quantity: 2,
            ExtendedPrice: 53461.32,
            Freight: 510.66,
            Discontinued: false,
            Region: `South East`,
            Address: `187 Wall Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 60100
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Home`,
            ShipAddress: `149 Main Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90150,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1032,
            CustomerName: `Mike Madison`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Madison`,
            CustomerAddress: `149 Main Street, Los Angeles, USA, 90150`,
            Salesperson: `Max Jefferson`,
            OrderID: 1886,
            OrderDate: `12/2/2022`,
            ProductID: 132,
            ProductName: `IPhone`,
            UnitPrice: 13760.64,
            Quantity: 3,
            ExtendedPrice: 41281.92,
            Freight: 1110.64,
            Discontinued: false,
            Region: `West`,
            Address: `149 Main Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90150
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Market`,
            ShipAddress: `124 Market Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 80175,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1033,
            CustomerName: `Martin Smith`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Smith`,
            CustomerAddress: `124 Market Street, Huston, USA, 80175`,
            Salesperson: `Nancy Smith`,
            OrderID: 1625,
            OrderDate: `11/9/2022`,
            ProductID: 100,
            ProductName: `IPad`,
            UnitPrice: 11590.58,
            Quantity: 3,
            ExtendedPrice: 34771.74,
            Freight: 1080.58,
            Discontinued: false,
            Region: `South East`,
            Address: `124 Market Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 80175
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Townhouse`,
            ShipAddress: `193 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 60165,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1034,
            CustomerName: `Max Watson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Watson`,
            CustomerAddress: `193 Wall Street, Philadelphia, USA, 60165`,
            Salesperson: `Martin Jackson`,
            OrderID: 1669,
            OrderDate: `7/3/2022`,
            ProductID: 157,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 19220.31,
            Quantity: 2,
            ExtendedPrice: 38440.62,
            Freight: 1130.31,
            Discontinued: false,
            Region: `South East`,
            Address: `193 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 60165
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Estate`,
            ShipAddress: `200 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 80146,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1035,
            CustomerName: `Max Jackson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `200 Wall Street, Philadelphia, USA, 80146`,
            Salesperson: `Pamela Jefferson`,
            OrderID: 1654,
            OrderDate: `1/7/2022`,
            ProductID: 155,
            ProductName: `IPhone`,
            UnitPrice: 7040.83,
            Quantity: 2,
            ExtendedPrice: 14081.66,
            Freight: 1420.83,
            Discontinued: false,
            Region: `North East`,
            Address: `200 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 80146
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Estate`,
            ShipAddress: `122 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 80150,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1036,
            CustomerName: `Nancy Smith`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Smith`,
            CustomerAddress: `122 Market Street, Los Angeles, USA, 80150`,
            Salesperson: `Martin Jackson`,
            OrderID: 1678,
            OrderDate: `12/14/2022`,
            ProductID: 120,
            ProductName: `Mac Book Air`,
            UnitPrice: 6530.89,
            Quantity: 3,
            ExtendedPrice: 19592.67,
            Freight: 250.89,
            Discontinued: false,
            Region: `North East`,
            Address: `122 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 80150
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Market`,
            ShipAddress: `128 Main Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 50068,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1037,
            CustomerName: `Max Jackson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `128 Main Street, Los Angeles, USA, 50068`,
            Salesperson: `Ben Watson`,
            OrderID: 1301,
            OrderDate: `1/25/2022`,
            ProductID: 166,
            ProductName: `IPad`,
            UnitPrice: 11420.23,
            Quantity: 2,
            ExtendedPrice: 22840.46,
            Freight: 950.23,
            Discontinued: false,
            Region: `South East`,
            Address: `128 Main Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 50068
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Home`,
            ShipAddress: `119 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 60180,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1038,
            CustomerName: `Pamela Smith`,
            CustomerFirstName: `Pamela`,
            CustomerLastName: `Smith`,
            CustomerAddress: `119 Market Street, Los Angeles, USA, 60180`,
            Salesperson: `Pamela Madison`,
            OrderID: 1385,
            OrderDate: `6/24/2022`,
            ProductID: 132,
            ProductName: `Mac Book Air`,
            UnitPrice: 29810.6,
            Quantity: 4,
            ExtendedPrice: 119242.4,
            Freight: 220.6,
            Discontinued: false,
            Region: `West`,
            Address: `119 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 60180
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Market`,
            ShipAddress: `115 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90168,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1039,
            CustomerName: `James Jefferson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `115 Market Street, Los Angeles, USA, 90168`,
            Salesperson: `Martin Smith`,
            OrderID: 1308,
            OrderDate: `8/13/2022`,
            ProductID: 109,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 20770.59,
            Quantity: 5,
            ExtendedPrice: 103852.95,
            Freight: 1690.59,
            Discontinued: true,
            Region: `North East`,
            Address: `115 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90168
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Estate`,
            ShipAddress: `128 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 50118,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1040,
            CustomerName: `Anna Watson`,
            CustomerFirstName: `Anna`,
            CustomerLastName: `Watson`,
            CustomerAddress: `128 Market Street, Los Angeles, USA, 50118`,
            Salesperson: `Pamela Black`,
            OrderID: 1519,
            OrderDate: `10/4/2022`,
            ProductID: 139,
            ProductName: `Mac Book Air`,
            UnitPrice: 14860.44,
            Quantity: 2,
            ExtendedPrice: 29720.88,
            Freight: 1670.44,
            Discontinued: false,
            Region: `South East`,
            Address: `128 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 50118
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Townhouse`,
            ShipAddress: `108 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90129,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1041,
            CustomerName: `Martin Smith`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Smith`,
            CustomerAddress: `108 Market Street, Los Angeles, USA, 90129`,
            Salesperson: `Nancy Black`,
            OrderID: 1118,
            OrderDate: `2/7/2022`,
            ProductID: 126,
            ProductName: `Mac Book Air`,
            UnitPrice: 28690.85,
            Quantity: 4,
            ExtendedPrice: 114763.4,
            Freight: 500.85,
            Discontinued: false,
            Region: `West`,
            Address: `108 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90129
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Market`,
            ShipAddress: `180 Main Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 50101,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1042,
            CustomerName: `Anna Smith`,
            CustomerFirstName: `Anna`,
            CustomerLastName: `Smith`,
            CustomerAddress: `180 Main Street, Los Angeles, USA, 50101`,
            Salesperson: `Martin Jefferson`,
            OrderID: 1541,
            OrderDate: `5/3/2022`,
            ProductID: 179,
            ProductName: `Mac Book Pro`,
            UnitPrice: 22630.28,
            Quantity: 3,
            ExtendedPrice: 67890.84,
            Freight: 1200.28,
            Discontinued: false,
            Region: `North East`,
            Address: `180 Main Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 50101
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Townhouse`,
            ShipAddress: `177 Market Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 90107,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1043,
            CustomerName: `Max Black`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Black`,
            CustomerAddress: `177 Market Street, Philadelphia, USA, 90107`,
            Salesperson: `Martin Jefferson`,
            OrderID: 1747,
            OrderDate: `5/11/2022`,
            ProductID: 133,
            ProductName: `Mac Book Pro`,
            UnitPrice: 6930.51,
            Quantity: 3,
            ExtendedPrice: 20791.53,
            Freight: 1660.51,
            Discontinued: false,
            Region: `South East`,
            Address: `177 Market Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 90107
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Estate`,
            ShipAddress: `134 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 70172,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1044,
            CustomerName: `Anna Jefferson`,
            CustomerFirstName: `Anna`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `134 Market Street, Miami, USA, 70172`,
            Salesperson: `Mike Smith`,
            OrderID: 1343,
            OrderDate: `10/11/2022`,
            ProductID: 190,
            ProductName: `Samsung Note`,
            UnitPrice: 26770.78,
            Quantity: 4,
            ExtendedPrice: 107083.12,
            Freight: 960.78,
            Discontinued: false,
            Region: `North East`,
            Address: `134 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 70172
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Estate`,
            ShipAddress: `117 Wall Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90124,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1045,
            CustomerName: `James Watson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Watson`,
            CustomerAddress: `117 Wall Street, Los Angeles, USA, 90124`,
            Salesperson: `Mike Watson`,
            OrderID: 1152,
            OrderDate: `2/25/2022`,
            ProductID: 101,
            ProductName: `Mac Book Pro`,
            UnitPrice: 8790.3,
            Quantity: 5,
            ExtendedPrice: 43951.5,
            Freight: 220.3,
            Discontinued: false,
            Region: `South East`,
            Address: `117 Wall Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90124
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Market`,
            ShipAddress: `156 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 60181,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1046,
            CustomerName: `James Black`,
            CustomerFirstName: `James`,
            CustomerLastName: `Black`,
            CustomerAddress: `156 Wall Street, Philadelphia, USA, 60181`,
            Salesperson: `Anna Smith`,
            OrderID: 1823,
            OrderDate: `10/12/2022`,
            ProductID: 178,
            ProductName: `Samsung Note`,
            UnitPrice: 9750.55,
            Quantity: 3,
            ExtendedPrice: 29251.65,
            Freight: 1940.55,
            Discontinued: false,
            Region: `North East`,
            Address: `156 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 60181
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Market`,
            ShipAddress: `122 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 90182,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1047,
            CustomerName: `Ben Madison`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Madison`,
            CustomerAddress: `122 Main Street, New York, USA, 90182`,
            Salesperson: `Mike Black`,
            OrderID: 1548,
            OrderDate: `5/1/2022`,
            ProductID: 181,
            ProductName: `Mac Book Air`,
            UnitPrice: 11590.37,
            Quantity: 4,
            ExtendedPrice: 46361.48,
            Freight: 900.37,
            Discontinued: false,
            Region: `West`,
            Address: `122 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 90182
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Townhouse`,
            ShipAddress: `112 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 60175,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1048,
            CustomerName: `Pamela Black`,
            CustomerFirstName: `Pamela`,
            CustomerLastName: `Black`,
            CustomerAddress: `112 Market Street, Los Angeles, USA, 60175`,
            Salesperson: `Mike Madison`,
            OrderID: 1581,
            OrderDate: `5/21/2022`,
            ProductID: 134,
            ProductName: `Mac Book Air`,
            UnitPrice: 8800.32,
            Quantity: 2,
            ExtendedPrice: 17600.64,
            Freight: 1820.32,
            Discontinued: false,
            Region: `South East`,
            Address: `112 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 60175
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Estate`,
            ShipAddress: `153 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90170,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1049,
            CustomerName: `Pamela Black`,
            CustomerFirstName: `Pamela`,
            CustomerLastName: `Black`,
            CustomerAddress: `153 Market Street, Los Angeles, USA, 90170`,
            Salesperson: `Pamela Watson`,
            OrderID: 1145,
            OrderDate: `11/13/2022`,
            ProductID: 151,
            ProductName: `Mac Book Air`,
            UnitPrice: 25830.42,
            Quantity: 3,
            ExtendedPrice: 77491.26,
            Freight: 270.42,
            Discontinued: true,
            Region: `North East`,
            Address: `153 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90170
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Estate`,
            ShipAddress: `159 Market Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 80198,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1050,
            CustomerName: `Anna Black`,
            CustomerFirstName: `Anna`,
            CustomerLastName: `Black`,
            CustomerAddress: `159 Market Street, Huston, USA, 80198`,
            Salesperson: `Pamela Jefferson`,
            OrderID: 1455,
            OrderDate: `12/16/2022`,
            ProductID: 115,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 28510.28,
            Quantity: 2,
            ExtendedPrice: 57020.56,
            Freight: 1450.28,
            Discontinued: false,
            Region: `West`,
            Address: `159 Market Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 80198
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Market`,
            ShipAddress: `125 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 70160,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1051,
            CustomerName: `Nancy Jefferson`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `125 Market Street, Miami, USA, 70160`,
            Salesperson: `Anna Jefferson`,
            OrderID: 1787,
            OrderDate: `1/3/2022`,
            ProductID: 171,
            ProductName: `Mac Book Air`,
            UnitPrice: 18830.35,
            Quantity: 3,
            ExtendedPrice: 56491.05,
            Freight: 1770.35,
            Discontinued: false,
            Region: `South East`,
            Address: `125 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 70160
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Home`,
            ShipAddress: `114 Wall Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 70083,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1052,
            CustomerName: `Nancy Jefferson`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `114 Wall Street, Los Angeles, USA, 70083`,
            Salesperson: `Anna Madison`,
            OrderID: 1591,
            OrderDate: `4/6/2022`,
            ProductID: 141,
            ProductName: `Mac Book Air`,
            UnitPrice: 18840.75,
            Quantity: 2,
            ExtendedPrice: 37681.5,
            Freight: 710.75,
            Discontinued: false,
            Region: `West`,
            Address: `114 Wall Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 70083
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jefferson Townhouse`,
            ShipAddress: `193 Main Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 70170,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1053,
            CustomerName: `James Jefferson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Jefferson`,
            CustomerAddress: `193 Main Street, Los Angeles, USA, 70170`,
            Salesperson: `Anna Jackson`,
            OrderID: 1020,
            OrderDate: `7/20/2022`,
            ProductID: 177,
            ProductName: `IPad`,
            UnitPrice: 15250.55,
            Quantity: 3,
            ExtendedPrice: 45751.65,
            Freight: 980.55,
            Discontinued: false,
            Region: `West`,
            Address: `193 Main Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 70170
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Home`,
            ShipAddress: `156 Main Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 50127,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1054,
            CustomerName: `Ben Smith`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Smith`,
            CustomerAddress: `156 Main Street, Huston, USA, 50127`,
            Salesperson: `James Black`,
            OrderID: 1770,
            OrderDate: `3/24/2022`,
            ProductID: 141,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 14910.59,
            Quantity: 5,
            ExtendedPrice: 74552.95,
            Freight: 1330.59,
            Discontinued: false,
            Region: `South East`,
            Address: `156 Main Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 50127
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Market`,
            ShipAddress: `146 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 60064,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1055,
            CustomerName: `Max Jackson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `146 Market Street, Miami, USA, 60064`,
            Salesperson: `Mike Smith`,
            OrderID: 1766,
            OrderDate: `10/23/2022`,
            ProductID: 141,
            ProductName: `Mac Book Air`,
            UnitPrice: 16740.86,
            Quantity: 3,
            ExtendedPrice: 50222.58,
            Freight: 580.86,
            Discontinued: false,
            Region: `West`,
            Address: `146 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 60064
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Estate`,
            ShipAddress: `163 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90158,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1056,
            CustomerName: `Max Black`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Black`,
            CustomerAddress: `163 Market Street, Los Angeles, USA, 90158`,
            Salesperson: `Martin Jefferson`,
            OrderID: 1415,
            OrderDate: `9/2/2022`,
            ProductID: 112,
            ProductName: `IPhone`,
            UnitPrice: 25190.37,
            Quantity: 3,
            ExtendedPrice: 75571.11,
            Freight: 1060.37,
            Discontinued: false,
            Region: `South East`,
            Address: `163 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90158
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Townhouse`,
            ShipAddress: `171 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 50163,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1057,
            CustomerName: `James Watson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Watson`,
            CustomerAddress: `171 Main Street, New York, USA, 50163`,
            Salesperson: `Martin Smith`,
            OrderID: 1430,
            OrderDate: `9/2/2022`,
            ProductID: 120,
            ProductName: `Samsung Note`,
            UnitPrice: 26340.71,
            Quantity: 2,
            ExtendedPrice: 52681.42,
            Freight: 770.71,
            Discontinued: false,
            Region: `North East`,
            Address: `171 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 50163
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Townhouse`,
            ShipAddress: `195 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 60159,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Speedy Express`,
            CustomerID: 1058,
            CustomerName: `James Black`,
            CustomerFirstName: `James`,
            CustomerLastName: `Black`,
            CustomerAddress: `195 Wall Street, Philadelphia, USA, 60159`,
            Salesperson: `Ben Black`,
            OrderID: 1903,
            OrderDate: `2/19/2022`,
            ProductID: 161,
            ProductName: `IPad`,
            UnitPrice: 6290.33,
            Quantity: 5,
            ExtendedPrice: 31451.65,
            Freight: 890.33,
            Discontinued: false,
            Region: `South East`,
            Address: `195 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 60159
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Watson Market`,
            ShipAddress: `171 Market Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 50154,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1059,
            CustomerName: `Pamela Watson`,
            CustomerFirstName: `Pamela`,
            CustomerLastName: `Watson`,
            CustomerAddress: `171 Market Street, Huston, USA, 50154`,
            Salesperson: `Anna Madison`,
            OrderID: 1578,
            OrderDate: `6/5/2022`,
            ProductID: 103,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 20240.82,
            Quantity: 5,
            ExtendedPrice: 101204.1,
            Freight: 1490.82,
            Discontinued: true,
            Region: `West`,
            Address: `171 Market Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 50154
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Market`,
            ShipAddress: `103 Market Street`,
            ShipCity: `New York`,
            ShipPostalCode: 70081,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1060,
            CustomerName: `Max Jackson`,
            CustomerFirstName: `Max`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `103 Market Street, New York, USA, 70081`,
            Salesperson: `Pamela Jackson`,
            OrderID: 1142,
            OrderDate: `4/1/2022`,
            ProductID: 108,
            ProductName: `IPhone`,
            UnitPrice: 9790.41,
            Quantity: 3,
            ExtendedPrice: 29371.23,
            Freight: 980.41,
            Discontinued: false,
            Region: `South East`,
            Address: `103 Market Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 70081
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Market`,
            ShipAddress: `187 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 70141,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1061,
            CustomerName: `Mike Smith`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Smith`,
            CustomerAddress: `187 Market Street, Los Angeles, USA, 70141`,
            Salesperson: `Ben Jefferson`,
            OrderID: 1871,
            OrderDate: `8/20/2022`,
            ProductID: 197,
            ProductName: `IPad`,
            UnitPrice: 28960.39,
            Quantity: 2,
            ExtendedPrice: 57920.78,
            Freight: 1280.39,
            Discontinued: false,
            Region: `West`,
            Address: `187 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 70141
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Estate`,
            ShipAddress: `145 Main Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 50068,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1062,
            CustomerName: `Ben Black`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Black`,
            CustomerAddress: `145 Main Street, Philadelphia, USA, 50068`,
            Salesperson: `Martin Watson`,
            OrderID: 1747,
            OrderDate: `1/20/2022`,
            ProductID: 198,
            ProductName: `Mac Book Pro`,
            UnitPrice: 12530.74,
            Quantity: 4,
            ExtendedPrice: 50122.96,
            Freight: 480.74,
            Discontinued: false,
            Region: `West`,
            Address: `145 Main Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 50068
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Home`,
            ShipAddress: `109 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 90197,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1063,
            CustomerName: `Nancy Black`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Black`,
            CustomerAddress: `109 Market Street, Los Angeles, USA, 90197`,
            Salesperson: `James Black`,
            OrderID: 1881,
            OrderDate: `11/6/2022`,
            ProductID: 162,
            ProductName: `Samsung Note`,
            UnitPrice: 29810.51,
            Quantity: 2,
            ExtendedPrice: 59621.02,
            Freight: 750.51,
            Discontinued: false,
            Region: `North East`,
            Address: `109 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 90197
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Market`,
            ShipAddress: `155 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 50184,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1064,
            CustomerName: `Nancy Smith`,
            CustomerFirstName: `Nancy`,
            CustomerLastName: `Smith`,
            CustomerAddress: `155 Market Street, Los Angeles, USA, 50184`,
            Salesperson: `Mike Madison`,
            OrderID: 1172,
            OrderDate: `5/14/2022`,
            ProductID: 154,
            ProductName: `IPhone`,
            UnitPrice: 11440.88,
            Quantity: 2,
            ExtendedPrice: 22881.76,
            Freight: 1570.88,
            Discontinued: false,
            Region: `West`,
            Address: `155 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 50184
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Estate`,
            ShipAddress: `136 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 60147,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1065,
            CustomerName: `James Jackson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `136 Main Street, New York, USA, 60147`,
            Salesperson: `James Jefferson`,
            OrderID: 1538,
            OrderDate: `2/4/2022`,
            ProductID: 142,
            ProductName: `IPad`,
            UnitPrice: 18340.25,
            Quantity: 5,
            ExtendedPrice: 91701.25,
            Freight: 1730.25,
            Discontinued: false,
            Region: `South East`,
            Address: `136 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 60147
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Market`,
            ShipAddress: `184 Wall Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 60091,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Speedy Express`,
            CustomerID: 1066,
            CustomerName: `Mike Madison`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Madison`,
            CustomerAddress: `184 Wall Street, Miami, USA, 60091`,
            Salesperson: `Ben Jackson`,
            OrderID: 1863,
            OrderDate: `2/6/2022`,
            ProductID: 186,
            ProductName: `Samsung Note`,
            UnitPrice: 6690.4,
            Quantity: 5,
            ExtendedPrice: 33452,
            Freight: 930.4,
            Discontinued: false,
            Region: `West`,
            Address: `184 Wall Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 60091
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Townhouse`,
            ShipAddress: `103 Market Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 80170,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1067,
            CustomerName: `James Jackson`,
            CustomerFirstName: `James`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `103 Market Street, Philadelphia, USA, 80170`,
            Salesperson: `Max Black`,
            OrderID: 1476,
            OrderDate: `1/13/2022`,
            ProductID: 156,
            ProductName: `Mac Book Pro`,
            UnitPrice: 29040.31,
            Quantity: 5,
            ExtendedPrice: 145201.55,
            Freight: 1070.31,
            Discontinued: false,
            Region: `West`,
            Address: `103 Market Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 80170
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Estate`,
            ShipAddress: `104 Market Street`,
            ShipCity: `Los Angeles`,
            ShipPostalCode: 80188,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `United Package`,
            CustomerID: 1068,
            CustomerName: `Ben Smith`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Smith`,
            CustomerAddress: `104 Market Street, Los Angeles, USA, 80188`,
            Salesperson: `Martin Watson`,
            OrderID: 1131,
            OrderDate: `9/13/2022`,
            ProductID: 131,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 6780.79,
            Quantity: 4,
            ExtendedPrice: 27123.16,
            Freight: 600.79,
            Discontinued: false,
            Region: `South East`,
            Address: `104 Market Street`,
            City: `Los Angeles`,
            Country: `USA`,
            PostalCode: 80188
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Madison Townhouse`,
            ShipAddress: `140 Main Street`,
            ShipCity: `New York`,
            ShipPostalCode: 90197,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1069,
            CustomerName: `Martin Madison`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Madison`,
            CustomerAddress: `140 Main Street, New York, USA, 90197`,
            Salesperson: `Anna Smith`,
            OrderID: 1829,
            OrderDate: `2/18/2022`,
            ProductID: 152,
            ProductName: `Samsung Note`,
            UnitPrice: 20150.52,
            Quantity: 4,
            ExtendedPrice: 80602.08,
            Freight: 1840.52,
            Discontinued: true,
            Region: `North East`,
            Address: `140 Main Street`,
            City: `New York`,
            Country: `USA`,
            PostalCode: 90197
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Market`,
            ShipAddress: `172 Wall Street`,
            ShipCity: `Philadelphia`,
            ShipPostalCode: 90159,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `United Package`,
            CustomerID: 1070,
            CustomerName: `Mike Smith`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Smith`,
            CustomerAddress: `172 Wall Street, Philadelphia, USA, 90159`,
            Salesperson: `Pamela Watson`,
            OrderID: 1082,
            OrderDate: `10/1/2022`,
            ProductID: 164,
            ProductName: `IPad`,
            UnitPrice: 23810.31,
            Quantity: 2,
            ExtendedPrice: 47620.62,
            Freight: 320.31,
            Discontinued: false,
            Region: `West`,
            Address: `172 Wall Street`,
            City: `Philadelphia`,
            Country: `USA`,
            PostalCode: 90159
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Market`,
            ShipAddress: `147 Wall Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 90173,
            ShipCountry: `USA`,
            ShipRegion: `South East`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1071,
            CustomerName: `Ben Jackson`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `147 Wall Street, Huston, USA, 90173`,
            Salesperson: `Martin Smith`,
            OrderID: 1449,
            OrderDate: `1/21/2022`,
            ProductID: 111,
            ProductName: `Mac Book Pro`,
            UnitPrice: 8280.25,
            Quantity: 4,
            ExtendedPrice: 33121,
            Freight: 860.25,
            Discontinued: false,
            Region: `South East`,
            Address: `147 Wall Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 90173
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Jackson Market`,
            ShipAddress: `161 Main Street`,
            ShipCity: `Huston`,
            ShipPostalCode: 90102,
            ShipCountry: `USA`,
            ShipRegion: `North East`,
            ShipperName: `United Package`,
            CustomerID: 1072,
            CustomerName: `Mike Jackson`,
            CustomerFirstName: `Mike`,
            CustomerLastName: `Jackson`,
            CustomerAddress: `161 Main Street, Huston, USA, 90102`,
            Salesperson: `Nancy Black`,
            OrderID: 1609,
            OrderDate: `9/22/2022`,
            ProductID: 197,
            ProductName: `Samsung Note`,
            UnitPrice: 16740.35,
            Quantity: 4,
            ExtendedPrice: 66961.4,
            Freight: 1940.35,
            Discontinued: false,
            Region: `North East`,
            Address: `161 Main Street`,
            City: `Huston`,
            Country: `USA`,
            PostalCode: 90102
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Smith Home`,
            ShipAddress: `102 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 70124,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1073,
            CustomerName: `Ben Smith`,
            CustomerFirstName: `Ben`,
            CustomerLastName: `Smith`,
            CustomerAddress: `102 Market Street, Miami, USA, 70124`,
            Salesperson: `Anna Smith`,
            OrderID: 1984,
            OrderDate: `8/6/2022`,
            ProductID: 123,
            ProductName: `Samsung Galaxy 22`,
            UnitPrice: 14660.66,
            Quantity: 3,
            ExtendedPrice: 43981.98,
            Freight: 1910.66,
            Discontinued: false,
            Region: `West`,
            Address: `102 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 70124
        }));
        this.push(new InvoicesDataItem(
        {
            ShipName: `Black Estate`,
            ShipAddress: `139 Market Street`,
            ShipCity: `Miami`,
            ShipPostalCode: 90134,
            ShipCountry: `USA`,
            ShipRegion: `West`,
            ShipperName: `Federal Shipping`,
            CustomerID: 1074,
            CustomerName: `Martin Black`,
            CustomerFirstName: `Martin`,
            CustomerLastName: `Black`,
            CustomerAddress: `139 Market Street, Miami, USA, 90134`,
            Salesperson: `Max Jackson`,
            OrderID: 1060,
            OrderDate: `3/11/2022`,
            ProductID: 154,
            ProductName: `Mac Book Pro`,
            UnitPrice: 14460.37,
            Quantity: 4,
            ExtendedPrice: 57841.48,
            Freight: 1020.37,
            Discontinued: false,
            Region: `West`,
            Address: `139 Market Street`,
            City: `Miami`,
            Country: `USA`,
            PostalCode: 90134
        }));
    }
}
